services:
  postgres:
    container_name: rag_postgres
    image: pgvector/pgvector:0.6.2-pg16
    platform: linux/amd64
    ports:
      - "5434:5432"
    volumes:
      - rag_postgres:/var/lib/postgresql/data
    hostname: rag_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ragdb

volumes:
  rag_postgres: